version: "3.8"

services:
  db:
    image: postgres:15
    container_name: financial_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financial_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml:
    build: ./services/ml
    container_name: financial_ml
    ports:
      - "8000:8000"

volumes:
  postgres_data: